### PR TITLE
move prebuild_nuc_data.h5 to this source

### PR DESCRIPTION
**Pull request by gonuke**
This file used to be served by data.pyne.io - it's being moved here and can be served from here with an update to the main pyne repo.  

I'm not sure how to confirm that this is the right `prebuild_nuc_data.h5` but it's one I have from a prior installation

### CODE REVIEW

**Comment by pshriwise** [comment]
Waiting until EOD to merge in case there are any other comments...

**Comment by pshriwise** [comment]
Actually, I tried this out locally on a branch of pyne with an updated url and I'm getting errors in `test_data.py` when using the prebuilt dataset. They're all along these lines:

```
======================================================================
FAIL: test_data.test_alpha_child_byen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shriwise/.local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/shriwise/opt/pyne/pyne/tests/test_data.py", line 386, in test_alpha_child_byen
    assert_equal(data.alpha_child_byen(5322.0, 0.1), [932370008, -952450000])
AssertionError: Lists differ: [932370008, 952450000] != [932370008, -952450000]

First differing element 1:
952450000
-952450000

- [932370008, 952450000]
+ [932370008, -952450000]
?             +

```

**Comment by gonuke** [comment]
I was afraid of that - maybe I have a version of the prebuilt data that is too old?

**Comment by gonuke** [comment]
superseded by #15 with newer file.

**Pull request closed without merging**
