### PR TITLE
Add `cram-apple-clang-arm.tar.gz` and `decay-apple-clang-arm.tar.gz`

### PR DESCRIPTION
**Pull request by bennibbelink**
Add decay and cram for arm Mac. Tested building cyclus using these assembly code files and no `--slow` flag is required.

### CODE REVIEW

**Comment by gonuke** [comment]
Does GitHub build on ARM for Mac? Could we demo/test this with a new GitHub action that uses these?

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think, we may create a workflow for each system using both GCC and Clang, and upload the artifacts to the repository.

**Comment by gonuke** [comment]
I mean something else: a workflow on the PyNE repository that build PyNE using this new data

**Comment by ahnaf-tahmid-chowdhury** [comment]
Unfortunately, to achieve this, we may need to merge this PR first so that PyNE can fetch these files. Alternatively, we could make them available in the workflow by fetching the files from cloud storage, such as Google Drive?

**Comment by gonuke** [comment]
@bennibbelink has experience with making things available temporarily for testing by pulling them from this branch.  Let's leave it to him to respond with his thoughts.

**Comment by bennibbelink** [comment]
GitHub does have intel and arm Mac runners that we could use (these are what cyclus uses for macOS workflows).

We can definitely add a workflow to Pyne to build Pyne on Mac.  It will require a little bit of coordination - the flow likely to be:
1. Make a branch in Pyne with a workflow that references this branch
2. confirm that it builds and passes tests
3. Merge this branch to `pyne/data:master` 
4. change the reference in the pyne workflow back to `master`
5. Merge Pyne branch (assuming all is well)

Should the Pyne MacOS workflow incorporate all of the optional Pyne dependencies? (e.g. Moab, openmc, dagmc) I'm not sure they support arm

**Comment by gonuke** [comment]
Good question about optional dependencies.  Let's start with none of them....

**Review by gonuke — APPROVED** [review]
Let's merge this... can't be worse than nothing & it will facilitate robust testing

**Pull request merged**
