### PR TITLE
adding new version of prebuilt_nuc_data.h5, that include mat numbers

### PR DESCRIPTION
**Pull request by bam241**
this uses the following python notebook (https://github.com/bam241/pyne_data/blob/master/pre_nuc_data.ipynb) to create a new version of the nuc_dat.h5 that includes mat numbers.

this allows uses a modified version of the pyne::MaterialLibrary see pyne/pyne#1334

### CODE REVIEW

**Comment by bam241** [comment]
the 2 material_library differences are tested in the python notebook.

**Comment by gonuke** [comment]
Can you add something to the notebook that shows that the old materials had no number and the new ones do?

**Comment by gonuke** [comment]
P.S. this is a nice quick fix - thanks!!

**Comment by bam241** [comment]
Sadly I cannot on this notebook: 
The fix on PyNE add the number when loading the material library in the pyne object

BUt I could in an other notebook to print the old material library and the new...

**Comment by bam241** [comment]
there it is:

https://github.com/bam241/pyne_data/blob/master/check_with_old_api.ipynb

**Comment by gonuke** [comment]
Thanks again @bam241

**Pull request merged**
