### PR TITLE
Adding nuc_data file.

### PR DESCRIPTION
**Pull request by pshriwise**
Offering this as a replacement for #13.

Can at least one of the reviewers pull down this file to make sure it works?

### CODE REVIEW

**Comment by pshriwise** [comment]
My understanding is that the `prebuilt_nuc_data.h5` essentially gets moved to the right location and renamed `nuc_data.h5` if it can be found by the `nuc_data_make` script in PyNE. 

That probably means this should be renamed to `prebuilt_nuc_data.h5` really.

...unless I'm off on this?

**Comment by zxkjack123** [comment]
I have tested the file, it works on my machine.

**Comment by pshriwise** [comment]
Any further comments here? I'd like to get this added and fix the CI sometime this week...

**Comment by gonuke** [comment]
My docker image is not behaving well enough for me to test this - but I'll take @zxkjack123's test as sufficient.  It can't be worse!

**Pull request merged**
