### PR TITLE
Updating prebuilt_nuc_data.h5 with mass.mas16 data

### PR DESCRIPTION
**Pull request by aruzzo**
Addresses issue #18:

- Updating `prebuilt_nuc_data.h5` to incorporate new atomic mass data from `mass.mas16`

I'm not sure what the verification process is for a big change to fundamental data, but I updated the few remaining failing tests from the original mass update PR [(failing tests here)](https://github.com/pyne/pyne/issues/1151#issuecomment-511584897) and ran `travis-run-tests.sh` and it passes the check [(CI Test)](https://circleci.com/workflow-run/2359d1c2-478e-4fac-beca-e534b1358316).

The nuc data file was updated by editing the existing `prebuilt_nuc_data.h5` file with pyne functions. I  edited the `make_atomic_mass` function in `pyne/dbgen/atomic_mass.py` to `pass` instead of `return` if the atomic_mass node already exists (which it does). Then, it deletes the prebuilt atomic mass node and reads in the data from `mass.mas16`. I then similarly edited `pyne/dbgen/materials_library.py` to `pass` instead of `return`, delete the prebuilt nodes, and then write in the new material library data.

### CODE REVIEW

**Comment by pshriwise** [comment]
I'm not sure how long it's been since this file was last changed, but as a start it'd be nice to have some kind of human-readable summary here in the PR with the changes to relevant datasets in the file as some kind of record for the scope of the changes and exact value updates if they need to be referenced in the future. A tool like `h5diff` might be able to help with that.

**Comment by aruzzo** [comment]
I used `h5diff` to try to compare the different nuc data files but the `atomic_mass` group now has a different size, so it's unable to compare them:

`dataset: </atomic_mass> and </atomic_mass>
Not comparable: </atomic_mass> has rank 1, dimensions [3466], max dimensions [18446744073709551615]
and </atomic_mass> has rank 1, dimensions [3549], max dimensions [18446744073709551615]`

**Comment by aruzzo** [comment]
I made a gist [(atomic_mass gist)](https://gist.github.com/aruzzo/67ae812d15961da9aca5a331a146edc0) that highlights the differences in atomic mass between the old and new `nuc_data.h5` files. It also prints the new `nuc_ids` that are present in the new file but not in the old one. For material_library, `h5diff` works in showing the difference for them. I don't know if there's a way to format the output, so I just piped it to a text file [(mat_lib gist)](https://gist.github.com/aruzzo/5151aab7d853026c1a6f5cd27e5f3880).

**Comment by gonuke** [comment]
Thanks @aruzzo - we are finally taking care of this during our hack-a-thon.

**Pull request merged**
